code_to_pdf.pdf:
	python -m code_to_pdf -o $@ $(realpath  code_to_pdf)
# TODO: relative paths does not work

flask.pdf:
	python -m code_to_pdf -o $@ $(realpath  flask)
# TODO: exclude some dirs: docs
