name: Code to pdf test
on: push
jobs:
    build-examples:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            # python-version: ["3.8", "3.11", "3.12", "3.13"]
            python-version: ["3.11"]
        steps:
            - name: Setup Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  sudo apt install texlive-full
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Install fonts
              run: |
                  ./.github/workflows/install_nerd_fonts.sh
            - name: Install package
              run: python -m pip install  ./
            - name: Build
              run: |
                   cd examples
                   REPO2TEX_FLAGS='--monofont "SauceCodePro Nerd Font Mono" --mainfont "SauceCodePro Nerd Font"' make
            - name: Archive PDFs
              uses: actions/upload-artifact@v4
              with:
                name: pdf
                path: |
                  examples/*.pdf
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Python
              uses: actions/setup-python@v4
            - name: Pre-commit
              run: |
                   pip install pre-commit
                   pre-commit install --install-hooks
                   pre-commit run --all-files
